language: node_js
node_js:
- 11.1.0
before_install:
- yarn global add codecov snyk greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- yarn lint-staged
- yarn test-unwatch
- yarn test-e2e-ci
script:
- yarn coverage
after_script:
# Prepare for GitHub
- openssl aes-256-cbc -K $encrypted_091c59dca5d1_key -iv $encrypted_091c59dca5d1_iv -in ./id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git config --global user.email "h.taku86@gmail.com"
- git config --global user.name "takuyahara"
- git config --global url."git@github.com:".insteadOf "https://github.com/"
# Build Storybook
- git checkout -b Storybook master
- mv netlify.storybook.toml netlify.toml
- git add .
- git commit -m "$TRAVIS_COMMIT_MESSAGE"
- git push -u origin Storybook --force
# Misc
- greenkeeper-lockfile-upload
- codecov
notifications:
  slack:
    secure: aIX+gBgrSuWWZhfAbMUPnSfHBDRhXj93RGOy+q+lYsvLiLIyMv0T/pwdra1OBkgQDkFef+4wboFtW24xhSFfsIY6C6AGzWPvFDJE9K+OlOPcRj4L2qByS7YYGan8AzdOCX4q2TClbvM59eBoLd3t+lT7PjBrAfHYWgBzFBfKTG8e4qweawSQhxZ2cxDmY9OftLjU3iMPF+CNMrzPfZPnWVDW9UeLqTR62crNaoW3120GLzniLinDNCCnWxUhbdxn+4fueaU4h1GzqIiGzLXIGgYLswvA0wGDALYtz9c0FYCCRogxD9Xl2LTPREgVhU2Ex05oHOBqpwO80tQzim6KEQ92jRPhwqhCkxFXV/0ZtvufB8+a3wcQTn+HbkUJ12ZDAMUicgBUjy4YJ9gM9AmID2RsAvr0G3VqivISqkeCtnSinmlDVY7MW24ACoil4MnWy5CxYrABFCXyxaeIq5XtZ3EzmWXdG6BXgxCyx4fd2Pvov1OOHhXiHHgLNumqizAyRxoLd5yy28zxnRwFeeNqCB6GVU5Qr2lDh01uNTUDgNMoaJ8FVkHfOF9eGwhEOT/6UCRINzFSXex01x2tasyPxczY4BCWNUXxhLv2hBcBV53+G8xKlmgzoQDh/aFCqIe+5keJ2Or0OWlZ9hpQWWkb0qyCvBl/reS+4ON+fjRy4aQ=
env:
  global:
  - secure: gAd4vnkSSaR2M6IP5/EPtw6TP+9YmrEHkkTt2MiNZrEO7EM8x5InQvTUrQfBFO1BP7bVyz9/gHE5eb1mTKWJR0/Xk837Cs2WUP53I5xNHihDHCJCs0xTai7P8Y/GnnJgNV6wOZALUnF8qOALYBf29h7aa0CsRDB/Qfvc7Z7Ev+pGB8bA2WUgFszktqbzhTVVNUGN+5jFDq7zwE+abEvg5cfmYZbxrjQHrXgIJzqhVfdRTqv1MueS2+dGAh1sEuebgIvUNstbZyLxB1oDnj1Yqn2vyUwhYUhqEuWmyziTvixupkr9pC79vQ6zHnyDirxHe1tRPsg8nDKvMH8zgD50P5wiv5dMemKrQ/iGB/HX/V1W0GYV7too8bPiENLdxvltP+bdy6v+Q0YKuh2wVJ70okJbmBLW3FwdXYuLs5ZjsLJiF7Jz89jKsSaVV7qn4+bA4OUnhBLDYo7q4bJRbZyBt+LPAaSAbHpusnN2k3qenjJDqJpK1AZMZ/HUUtgo+ExJMKdnb8xzACaBt+alo27uTmQ0j+C3uCy+NcwVyMA8Fhjjr6i63KI+qwFmtE4WWYr99De6J7Sz/Lo2qEUyI6dpHk1PuY7QIKsG5STJDAH89uy80r8kFA0KWQVjb+1ytsYeYXWVfSONPiGz10OmsAaDwZdoRjasjWIfY/VImNrFGCs=
